const GAME_CONSTANTS = {
  CANVAS_WIDTH: 1280,
  CANVAS_HEIGHT: 720,
  TILE_SIZE: 40,
  
  PLAYER: {
    SPEED: 150,
    RUN_SPEED: 250,
    CROUCH_SPEED: 80,
    MAX_HEALTH: 100,
    MAX_STAMINA: 100,
    MAX_ARMOR: 100,
    STAMINA_DRAIN_RUN: 20,
    STAMINA_REGEN: 30,
    SIZE: 15,
    MELEE_RANGE: 50,
    MELEE_COOLDOWN: 0.5,
    BLEEDING_DAMAGE_RATE: 5,
    BLEED_DURATION: 10
  },
  
  WEAPONS: {
    GLOCK: {
      name: 'Glock',
      damage: 15,
      fireRate: 0.1,
      magazineSize: 17,
      reloadTime: 1.2,
      accuracy: 0.85,
      bulletSpread: 0.15,
      recoil: 2,
      muzzleFlashSize: 20,
      type: 'pistol',
      rarity: 'common',
      icon: '🔫'
    },
    DESERT_EAGLE: {
      name: 'Desert Eagle',
      damage: 45,
      fireRate: 0.15,
      magazineSize: 7,
      reloadTime: 1.8,
      accuracy: 0.8,
      bulletSpread: 0.2,
      recoil: 5,
      muzzleFlashSize: 25,
      type: 'pistol',
      rarity: 'rare',
      icon: '🔫'
    },
    MP5: {
      name: 'MP5',
      damage: 12,
      fireRate: 0.05,
      magazineSize: 30,
      reloadTime: 1.5,
      accuracy: 0.75,
      bulletSpread: 0.25,
      recoil: 1,
      muzzleFlashSize: 15,
      type: 'smg',
      rarity: 'uncommon',
      icon: '🔫'
    },
    UMP45: {
      name: 'UMP45',
      damage: 18,
      fireRate: 0.06,
      magazineSize: 25,
      reloadTime: 1.4,
      accuracy: 0.72,
      bulletSpread: 0.3,
      recoil: 1.5,
      muzzleFlashSize: 16,
      type: 'smg',
      rarity: 'uncommon',
      icon: '🔫'
    },
    M4A1: {
      name: 'M4A1',
      damage: 28,
      fireRate: 0.08,
      magazineSize: 30,
      reloadTime: 1.6,
      accuracy: 0.88,
      bulletSpread: 0.12,
      recoil: 2.5,
      muzzleFlashSize: 22,
      type: 'rifle',
      rarity: 'uncommon',
      icon: '🔫'
    },
    AK47: {
      name: 'AK-47',
      damage: 35,
      fireRate: 0.09,
      magazineSize: 30,
      reloadTime: 1.8,
      accuracy: 0.75,
      bulletSpread: 0.18,
      recoil: 3.5,
      muzzleFlashSize: 24,
      type: 'rifle',
      rarity: 'uncommon',
      icon: '🔫'
    },
    SCARL: {
      name: 'SCAR-L',
      damage: 32,
      fireRate: 0.08,
      magazineSize: 20,
      reloadTime: 1.7,
      accuracy: 0.89,
      bulletSpread: 0.11,
      recoil: 2.3,
      muzzleFlashSize: 23,
      type: 'rifle',
      rarity: 'rare',
      icon: '🔫'
    },
    PUMP_SHOTGUN: {
      name: 'Pump Shotgun',
      damage: 80,
      fireRate: 0.8,
      magazineSize: 8,
      reloadTime: 0.5,
      accuracy: 0.5,
      bulletSpread: 0.6,
      recoil: 8,
      muzzleFlashSize: 30,
      type: 'shotgun',
      rarity: 'uncommon',
      icon: '🔫'
    },
    AUTO_SHOTGUN: {
      name: 'Auto Shotgun',
      damage: 60,
      fireRate: 0.4,
      magazineSize: 8,
      reloadTime: 1.2,
      accuracy: 0.48,
      bulletSpread: 0.65,
      recoil: 6,
      muzzleFlashSize: 28,
      type: 'shotgun',
      rarity: 'rare',
      icon: '🔫'
    },
    AWP: {
      name: 'AWP',
      damage: 120,
      fireRate: 1.2,
      magazineSize: 10,
      reloadTime: 2.5,
      accuracy: 0.95,
      bulletSpread: 0.05,
      recoil: 7,
      muzzleFlashSize: 20,
      type: 'sniper',
      rarity: 'rare',
      icon: '🔫'
    },
    M24: {
      name: 'M24',
      damage: 100,
      fireRate: 1.5,
      magazineSize: 5,
      reloadTime: 2.2,
      accuracy: 0.93,
      bulletSpread: 0.06,
      recoil: 6,
      muzzleFlashSize: 19,
      type: 'sniper',
      rarity: 'rare',
      icon: '🔫'
    },
    MINIGUN: {
      name: 'Minigun',
      damage: 18,
      fireRate: 0.02,
      magazineSize: 200,
      reloadTime: 3,
      accuracy: 0.65,
      bulletSpread: 0.35,
      recoil: 0.5,
      muzzleFlashSize: 25,
      type: 'heavy',
      rarity: 'epic',
      icon: '🔫'
    },
    ROCKET_LAUNCHER: {
      name: 'Rocket Launcher',
      damage: 150,
      fireRate: 2,
      magazineSize: 6,
      reloadTime: 2,
      accuracy: 0.85,
      bulletSpread: 0.1,
      recoil: 10,
      muzzleFlashSize: 40,
      type: 'heavy',
      rarity: 'epic',
      icon: '🚀'
    },
    GRENADE_LAUNCHER: {
      name: 'Grenade Launcher',
      damage: 100,
      fireRate: 0.5,
      magazineSize: 6,
      reloadTime: 2.2,
      accuracy: 0.8,
      bulletSpread: 0.15,
      recoil: 8,
      muzzleFlashSize: 35,
      type: 'heavy',
      rarity: 'epic',
      icon: '💣'
    },
    GRENADE: {
      name: 'Grenade',
      damage: 80,
      fireRate: 2,
      magazineSize: 5,
      reloadTime: 0,
      accuracy: 0.7,
      bulletSpread: 0.2,
      recoil: 4,
      muzzleFlashSize: 30,
      type: 'explosive',
      rarity: 'common',
      icon: '💣'
    },
    MOLOTOV: {
      name: 'Molotov Cocktail',
      damage: 40,
      fireRate: 2.5,
      magazineSize: 5,
      reloadTime: 0,
      accuracy: 0.75,
      bulletSpread: 0.15,
      recoil: 2,
      muzzleFlashSize: 25,
      type: 'explosive',
      rarity: 'uncommon',
      icon: '🔥'
    }
  },
  
  ZOMBIES: {
    WALKER: {
      name: 'Walker',
      health: 30,
      speed: 80,
      damage: 10,
      attackCooldown: 1.5,
      range: 30,
      size: 12,
      xpReward: 10,
      moneyReward: 5,
      icon: '🧟'
    },
    RUNNER: {
      name: 'Runner',
      health: 25,
      speed: 180,
      damage: 15,
      attackCooldown: 1.2,
      range: 35,
      size: 11,
      xpReward: 20,
      moneyReward: 10,
      icon: '🧟‍♂️'
    },
    TANK: {
      name: 'Tank',
      health: 150,
      speed: 60,
      damage: 30,
      attackCooldown: 2,
      range: 40,
      size: 20,
      xpReward: 50,
      moneyReward: 50,
      icon: '🧟'
    },
    SPITTER: {
      name: 'Spitter',
      health: 40,
      speed: 100,
      damage: 8,
      attackCooldown: 1.5,
      range: 200,
      size: 13,
      xpReward: 25,
      moneyReward: 15,
      icon: '🧟'
    },
    SCREAMER: {
      name: 'Screamer',
      health: 20,
      speed: 120,
      damage: 5,
      attackCooldown: 0.5,
      range: 400,
      size: 10,
      xpReward: 15,
      moneyReward: 8,
      icon: '🧟'
    },
    EXPLODER: {
      name: 'Exploder',
      health: 35,
      speed: 90,
      damage: 50,
      attackCooldown: 3,
      range: 150,
      size: 14,
      xpReward: 40,
      moneyReward: 30,
      icon: '💥'
    },
    BOSS: {
      name: 'Mutant Boss',
      health: 500,
      speed: 120,
      damage: 60,
      attackCooldown: 1,
      range: 50,
      size: 25,
      xpReward: 200,
      moneyReward: 200,
      icon: '👹'
    }
  },
  
  MAPS: [
    { name: 'Abandoned City', difficulty: 'Normal', width: 3000, height: 3000 },
    { name: 'Military Base', difficulty: 'Hard', width: 2500, height: 2500 },
    { name: 'Hospital', difficulty: 'Normal', width: 2000, height: 2500 },
    { name: 'School', difficulty: 'Easy', width: 2500, height: 2000 },
    { name: 'Shopping Mall', difficulty: 'Hard', width: 3500, height: 3000 },
    { name: 'Forest', difficulty: 'Medium', width: 4000, height: 3500 },
    { name: 'Farm', difficulty: 'Easy', width: 3000, height: 2500 },
    { name: 'Subway Station', difficulty: 'Medium', width: 2500, height: 2000 },
    { name: 'Research Lab', difficulty: 'Hard', width: 2000, height: 2500 },
    { name: 'Harbor', difficulty: 'Hard', width: 3500, height: 2500 },
    { name: 'Desert Outpost', difficulty: 'Medium', width: 3000, height: 3000 },
    { name: 'Snow Village', difficulty: 'Hard', width: 2500, height: 2500 }
  ],
  
  LOOT_TYPES: [
    'ammo', 'health_kit', 'bandage', 'armor', 'weapon',
    'food', 'water', 'weapon_part', 'backpack', 'money', 'fuel'
  ],
  
  WEATHER_TYPES: ['clear', 'rain', 'storm', 'fog', 'snow'],
  
  RARITIES: ['common', 'uncommon', 'rare', 'epic', 'legendary']
};
